from flask import render_template
from app import app

# Views
@app.route("/")
def index():

    """
    View root page function that returns the index page and its data
    """
    sources = [
        {
            "id": "abc-news",
            "name": "ABC News",
            "description": "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            "url": "https://abcnews.go.com",
            "category": "general",
            "language": "en",
            "country": "us",
        },
        {
            "id": "abc-news-au",
            "name": "ABC News (AU)",
            "description": "Australia's most trusted source of local, national and world news. Comprehensive, independent, in-depth analysis, the latest business, sport, weather and more.",
            "url": "http://www.abc.net.au/news",
            "category": "general",
            "language": "en",
            "country": "au",
        },
        {
            "id": "aftenposten",
            "name": "Aftenposten",
            "description": "Norges ledende nettavis med alltid oppdaterte nyheter innenfor innenriks, utenriks, sport og kultur.",
            "url": "https://www.aftenposten.no",
            "category": "general",
            "language": "no",
            "country": "no",
        },
        {
            "id": "al-jazeera-english",
            "name": "Al Jazeera English",
            "description": "News, analysis from the Middle East and worldwide, multimedia and interactives, opinions, documentaries, podcasts, long reads and broadcast schedule.",
            "url": "http://www.aljazeera.com",
            "category": "general",
            "language": "en",
            "country": "us",
        },
        {
            "id": "ansa",
            "name": "ANSA.it",
            "description": "Agenzia ANSA: ultime notizie, foto, video e approfondimenti su: cronaca, politica, economia, regioni, mondo, sport, calcio, cultura e tecnologia.",
            "url": "http://www.ansa.it",
            "category": "general",
            "language": "it",
            "country": "it",
        },
        {
            "id": "argaam",
            "name": "Argaam",
            "description": "ارقام موقع متخصص في متابعة سوق الأسهم السعودي تداول - تاسي - مع تغطيه معمقة لشركات واسعار ومنتجات البتروكيماويات , تقارير مالية الاكتتابات الجديده ",
            "url": "http://www.argaam.com",
            "category": "business",
            "language": "ar",
            "country": "sa",
        },
        {
            "id": "ars-technica",
            "name": "Ars Technica",
            "description": "The PC enthusiast's resource. Power users and the tools they love, without computing religion.",
            "url": "http://arstechnica.com",
            "category": "technology",
            "language": "en",
            "country": "us",
        },
        {
            "id": "ary-news",
            "name": "Ary News",
            "description": "ARY News is a Pakistani news channel committed to bring you up-to-the minute Pakistan news and featured stories from around Pakistan and all over the world.",
            "url": "https://arynews.tv/ud/",
            "category": "general",
            "language": "ud",
            "country": "pk",
        },
        {
            "id": "associated-press",
            "name": "Associated Press",
            "description": "The AP delivers in-depth coverage on the international, politics, lifestyle, business, and entertainment news.",
            "url": "https://apnews.com/",
            "category": "general",
            "language": "en",
            "country": "us",
        },
    ]

    articles = [
        {
            "source": {"id": "the-next-web", "name": "The Next Web"},
            "author": "The Markup",
            "title": 'What does it actually mean when a company says, "We do not sell your data"?',
            "description": "You’ve likely run into this claim from tech giants before: “We do not sell your personal data.”\r\n\r\nCompanies from Facebook to Google to Twitter repeat versions of this statement ...",
            "url": "https://thenextweb.com/news/what-mean-when-company-says-we-do-not-sell-your-data-syndication",
            "urlToImage": "https://img-cdn.tnwcdn.com/image/tnw?filter_last=1&fit=1280%2C640&url=https%3A%2F%2Fcdn0.tnwcdn.com%2Fwp-content%2Fblogs.dir%2F1%2Ffiles%2F2021%2F09%2FCompanies-selling-your-data-illustration-person-face-money.jpg&signature=0ef52b42dc6f6de38b21e7d56f3f554a",
            "publishedAt": "2021-09-12T10:00:29Z",
            "content": "Youve likely run into this claim from tech giants before: We do not sell your personal data.\r\nCompanies from Facebook to Google to Twitter repeat versions of this statement in their privacy policies,… [+10584 chars]",
        },
        {
            "source": {"id": "techcrunch", "name": "TechCrunch"},
            "author": "Natasha Mascarenhas",
            "title": "The next big startup may just help venture back more startups - TechCrunch",
            "description": "Welcome to Startups Weekly, a fresh human-first take on this week’s startup news and trends. To get this in your inbox, subscribe here.  Oper8r, built by Winter Mead and Welly Sculley, wants to help new entrants in the VC world scale. The accelerator launched…",
            "url": "http://techcrunch.com/2021/09/11/the-next-big-startup-may-just-help-venture-back-more-startups/",
            "urlToImage": "https://techcrunch.com/wp-content/uploads/2021/09/money_ometer.jpg?w=533",
            "publishedAt": "2021-09-11T18:02:22Z",
            "content": "Welcome to Startups Weekly, a fresh human-first take on this weeks startup news and trends. To get this in your inbox, subscribe here. \r\nOper8r, built by Winter Mead and Welly Sculley, wants to help … [+5958 chars]",
        },
        {
            "source": {"id": "techcrunch", "name": "TechCrunch"},
            "author": "Sarah Perez",
            "title": "Epic trial forces App Store changes, Android 12 launch nears, Twitter tries communities",
            "description": "Welcome back to This Week in Apps, the weekly TechCrunch series that recaps the latest in mobile OS news, mobile applications and the overall app economy. The app industry continues to grow, with a record 218 billion downloads and $143 billion in global consu…",
            "url": "http://techcrunch.com/2021/09/11/this-week-in-apps-epic-trial-forces-app-store-changes-android-12-launch-nears-twitter-tries-communities/",
            "urlToImage": "https://techcrunch.com/wp-content/uploads/2021/08/this-week-in-apps-splash-3.png?w=753",
            "publishedAt": "2021-09-11T17:35:08Z",
            "content": "Welcome back to This Week in Apps, the weekly TechCrunch series that recaps the latest in mobile OS news, mobile applications and the overall app economy.\r\nThe app industry continues to grow, with a … [+23324 chars]",
        },
        {
            "source": {"id": "techcrunch", "name": "TechCrunch"},
            "author": "Anna Heim",
            "title": "BNPL everywhere",
            "description": "While the biggest news was undoubtedly PayPal's decision to acquire Japan's Paidy for $2.7 billion, Amazon closing a deal with Max Levchin's Affirm was also ...",
            "url": "https://techcrunch.com/2021/09/11/2201091/",
            "urlToImage": "https://s.yimg.com/ny/api/res/1.2/4bMyPsF..ciaap90FUpDyQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD05MDA-/https://s.yimg.com/uu/api/res/1.2/.NFicuazeBq4sAQjASyTJg--~B/aD0yMTYwO3c9Mjg4MDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/techcrunch_350/5e9dfb680a32786ecdcf5aa690fa0f34",
            "publishedAt": "2021-09-11T17:01:55Z",
            "content": "Welcome back to The TechCrunch Exchange, a weekly startups-and-markets newsletter. Its inspired by what the weekday Exchange column digs into, but free, and made for your weekend reading. Want it in … [+7072 chars]",
        },
        {
            "source": {"id": "techcrunch", "name": "TechCrunch"},
            "author": "Maria Rioumine",
            "title": "Tech can help solve US cities’ affordability crisis - TechCrunch",
            "description": "Maria Rioumine Contributor Share on Twitter Maria Rioumine is the CEO and co-founder of Agora. U.S. cities are in the midst of an affordability crisis. Just between May 2020 and May 2021, home prices saw their biggest annual increase in more than two decades …",
            "url": "http://techcrunch.com/2021/09/11/tech-can-help-solve-us-cities-affordability-crisis/",
            "urlToImage": "https://techcrunch.com/wp-content/uploads/2021/09/GettyImages-1193602662.jpg?w=599",
            "publishedAt": "2021-09-11T17:00:39Z",
            "content": "U.S. cities are in the midst of an affordability crisis. Just between May 2020 and May 2021, home prices saw their biggest annual increase in more than two decades and construction material prices in… [+4401 chars]",
        },
        {
            "source": {"id": "techcrunch", "name": "TechCrunch"},
            "author": "Maria Rioumine",
            "title": "Tech can help solve US cities' affordability crisis",
            "description": "U.S. cities are in the midst of an affordability crisis.  Just between May 2020 and May 2021, home prices saw their biggest annual increase in more than two ...",
            "url": "https://techcrunch.com/2021/09/11/tech-can-help-solve-us-cities-affordability-crisis/",
            "urlToImage": "https://s.yimg.com/ny/api/res/1.2/Zixcd.5wUoYtg3.sSmLDow--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDE-/https://s.yimg.com/uu/api/res/1.2/hR2BsQR0ANfVCV5IH6OHLQ--~B/aD04MjE7dz0xMjMwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/techcrunch_350/f569c142614954f98a070e06ac08afb5",
            "publishedAt": "2021-09-11T16:59:57Z",
            "content": "U.S. cities are in the midst of an affordability crisis. Just between May 2020 and May 2021, home prices saw their biggest annual increase in more than two decades and construction material prices in… [+4403 chars]",
        },
        {
            "source": {"id": "techcrunch", "name": "TechCrunch"},
            "author": "Rita Liao",
            "title": "China roundup: Tencent takes on sites trying to circumvent its age limits – TechCrunch",
            "description": "Hello and welcome back to TechCrunch’s China roundup, a digest of recent events shaping the Chinese tech landscape and what they mean to people in the rest of the world. The enforcement of China’s new gaming regulations is unfolding like a cat-and-mouse game,…",
            "url": "http://techcrunch.com/2021/09/11/china-roundup-tencent-takes-on-sites-trying-to-circumvent-its-age-limits/",
            "urlToImage": "https://techcrunch.com/wp-content/uploads/2021/09/GettyImages-805984782.jpg?w=600",
            "publishedAt": "2021-09-11T16:11:02Z",
            "content": "Hello and welcome back to TechCrunchs China roundup, a digest of recent events shaping the Chinese tech landscape and what they mean to people in the rest of the world.\r\nThe enforcement of China’s ne… [+5227 chars]",
        },
        {
            "source": {"id": "techcrunch", "name": "TechCrunch"},
            "author": "Rita Liao",
            "title": "China roundup: Tencent takes on sites trying to circumvent its age limits",
            "description": "The enforcement of China's new gaming regulations is unfolding like a cat-and-mouse game, with the country's internet giants and young players constantly...",
            "url": "https://techcrunch.com/2021/09/11/china-roundup-tencent-takes-on-sites-trying-to-circumvent-its-age-limits/",
            "urlToImage": "https://s.yimg.com/ny/api/res/1.2/KTb2mQ8m5vRAlpb2v0v6rA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://s.yimg.com/uu/api/res/1.2/N39_ZVRSr2HkhacVjuzKSQ--~B/aD0yODgwO3c9NDMyMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/techcrunch_350/6a6e6ed3d67c3c83a0c4fc12d29df014",
            "publishedAt": "2021-09-11T16:11:02Z",
            "content": "Hello and welcome back to TechCrunchs China roundup, a digest of recent events shaping the Chinese tech landscape and what they mean to people in the rest of the world.\r\nThe enforcement of China's ne… [+5228 chars]",
        },
        {
            "source": {"id": "techcrunch", "name": "TechCrunch"},
            "author": "Danny Crichton",
            "title": "What’s happening in venture law in 2021?",
            "description": "The venture world is growing faster than ever, with more funding rounds, bigger funding rounds, and higher valuations than pretty much any point in history...",
            "url": "https://techcrunch.com/2021/09/11/whats-happening-in-venture-law-in-2021/",
            "urlToImage": "https://s.yimg.com/ny/api/res/1.2/AvUSKpofh2vdWId1_SH0_A--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://s.yimg.com/uu/api/res/1.2/p.URrt1zuuwLlvB7OozEGw--~B/aD0zMDAwO3c9NDUwMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/techcrunch_350/b8a9e394050c2b922a8e68c7fab8898a",
            "publishedAt": "2021-09-11T14:06:19Z",
            "content": "The venture world is growing faster than ever, with more funding rounds, bigger funding rounds, and higher valuations than pretty much any point in history. Thats led to an exponential growth in the … [+3027 chars]",
        },
        {
            "source": {"id": "techcrunch", "name": "TechCrunch"},
            "author": "Danny Crichton",
            "title": "What’s happening in venture law in 2021? – TechCrunch",
            "description": "The venture world is growing faster than ever, with more funding rounds, bigger funding rounds, and higher valuations than pretty much any point in history. That’s led to an exponential growth in the number of unicorns walking around, and has also forced regu…",
            "url": "http://techcrunch.com/2021/09/11/whats-happening-in-venture-law-in-2021/",
            "urlToImage": "https://techcrunch.com/wp-content/uploads/2021/09/GettyImages-1147500502.jpg?w=600",
            "publishedAt": "2021-09-11T14:06:19Z",
            "content": "The venture world is growing faster than ever, with more funding rounds, bigger funding rounds, and higher valuations than pretty much any point in history. Thats led to an exponential growth in the … [+3019 chars]",
        },
        {
            "source": {"id": "techcrunch", "name": "TechCrunch"},
            "author": "Alexander I. Platt",
            "title": "The legal world needs to shed its ‘unicorniphobia’ – TechCrunch",
            "description": "As policymakers and scholars work out how securities regulation can be used to address climate change, they should not overlook the potentially important role unicorn regulation can play.",
            "url": "http://techcrunch.com/2021/09/11/the-legal-world-needs-to-shed-its-unicorniphobia/",
            "urlToImage": "https://techcrunch.com/wp-content/uploads/2021/09/GettyImages-1290568962.jpg?w=536",
            "publishedAt": "2021-09-11T14:06:06Z",
            "content": "Once upon a time, a successful startup that reached a certain maturity would go public selling securities to ordinary investors, perhaps listing on a national stock exchange and taking on the privile… [+7103 chars]",
        },
        {
            "source": {"id": "techcrunch", "name": "TechCrunch"},
            "author": "Alexander I. Platt",
            "title": "The legal world needs to shed its 'unicorniphobia'",
            "description": "Once upon a time, a successful startup that reached a certain maturity would “go public” — selling securities to ordinary investors, perhaps listing on a...",
            "url": "https://techcrunch.com/2021/09/11/the-legal-world-needs-to-shed-its-unicorniphobia/",
            "urlToImage": "https://s.yimg.com/ny/api/res/1.2/mO4JsO_i64wILO4hOxZQdA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04OTY-/https://s.yimg.com/uu/api/res/1.2/e4cHCvtYSn0Z8Ye_gKrHyA--~B/aD0yODAwO3c9Mzc1MDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/techcrunch_350/98ed67fdcd055334a2caab712755f956",
            "publishedAt": "2021-09-11T14:05:58Z",
            "content": "Once upon a time, a successful startup that reached a certain maturity would go public selling securities to ordinary investors, perhaps listing on a national stock exchange and taking on the privile… [+7103 chars]",
        },
        {
            "source": {"id": "the-next-web", "name": "The Next Web"},
            "author": "TNW Deals",
            "title": "iBrave offers unlimited cloud hosting abilities for under $100",
            "description": "TLDR: Lock in safe, effective web hosting for life for one website or any unlimited number of sites with support from iBrave Hosting for as little as $24.99. Web hosting is one of those misunderstood web essentials that never seems like a big deal until the m…",
            "url": "https://thenextweb.com/news/ibrave-offers-unlimited-cloud-hosting-abilities-for-under-100",
            "urlToImage": "https://img-cdn.tnwcdn.com/image/tnw-deals?filter_last=1&fit=1280%2C640&url=https%3A%2F%2Fcdn0.tnwcdn.com%2Fwp-content%2Fblogs.dir%2F1%2Ffiles%2F2021%2F09%2Ftnw-iBraveCloud.jpeg&signature=96fb895571f6e118ad6faebf9dbf6914",
            "publishedAt": "2021-09-11T14:00:20Z",
            "content": "TLDR: Lock in safe, effective web hosting for life for one website or any unlimited number of sites with support from iBrave Hosting for as little as $24.99.\r\nWeb hosting is one of those misunderstoo… [+2487 chars]",
        },
        {
            "source": {"id": "the-next-web", "name": "The Next Web"},
            "author": "The Conversation",
            "title": "I’d prefer an ankle tag over a quarantine app",
            "description": "South Australia has begun a trial of a new COVID app to monitor arrivals into the state. SA Premier Steven Marshall claimed, “every South Australian should feel pretty proud that we are the national pilot for the home-based quarantine app”. He then doubled do…",
            "url": "https://thenextweb.com/news/id-prefer-an-ankle-tag-over-a-quarantine-app",
            "urlToImage": "https://img-cdn.tnwcdn.com/image/tnw?filter_last=1&fit=1280%2C640&url=https%3A%2F%2Fcdn0.tnwcdn.com%2Fwp-content%2Fblogs.dir%2F1%2Ffiles%2F2021%2F09%2FHomeQuarantine.jpg&signature=fb21b3d8f7ea722db4c0a9089eaf0826",
            "publishedAt": "2021-09-11T13:00:56Z",
            "content": "South Australia has begun a trial of a new COVID app to monitor arrivals into the state. SA Premier Steven Marshall claimed, every South Australian should feel pretty proud that we are the national p… [+5761 chars]",
        },
        {
            "source": {"id": "techcrunch", "name": "TechCrunch"},
            "author": "John Ackerly",
            "title": "20 years later, unchecked data collection is part of 9/11’s legacy – TechCrunch",
            "description": 'Twenty years from now, will we look back on this decade as a turning point in protecting and upholding individuals\' right to privacy, or will we still be saying, "Never again," again and again?',
            "url": "http://techcrunch.com/2021/09/11/20-years-later-unchecked-data-collection-is-part-of-9-11s-legacy/",
            "urlToImage": "https://techcrunch.com/wp-content/uploads/2021/09/GettyImages-930192500.jpg?w=711",
            "publishedAt": "2021-09-11T12:15:32Z",
            "content": "Almost every American adult remembers, in vivid detail, where they were the morning of September 11, 2001. I was on the second floor of the West Wing of the White House, at a National Economic Counci… [+8293 chars]",
        },
        {
            "source": {"id": "techcrunch", "name": "TechCrunch"},
            "author": "John Ackerly",
            "title": "20 years later, unchecked data collection is part of 9/11's legacy",
            "description": "Almost every American adult remembers, in vivid detail, where they were the morning of September 11, 2001.  Just an hour before, as the National Economic...",
            "url": "https://techcrunch.com/2021/09/11/20-years-later-unchecked-data-collection-is-part-of-9-11s-legacy/",
            "urlToImage": "https://s.yimg.com/ny/api/res/1.2/yRKhgjupaYaT5YFwrSJZ_Q--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://s.yimg.com/uu/api/res/1.2/J7CZ37lFZc88pHmcQoNw1Q--~B/aD03ODg7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/techcrunch_350/77f1cc16c7bc2b7eefa3dd7f40a0b388",
            "publishedAt": "2021-09-11T12:15:06Z",
            "content": "Almost every American adult remembers, in vivid detail, where they were the morning of September 11, 2001. I was on the second floor of the West Wing of the White House, at a National Economic Counci… [+8293 chars]",
        },
        {
            "source": {"id": "the-next-web", "name": "The Next Web"},
            "author": "The Conversation",
            "title": "5 reasons why video games should be mandatory in every classroom",
            "description": "In an effort to curtail how much time young people spend playing video games, China has banned students from playing them during the school week and limits them to just one hour per day on Fridays, weekends and holidays. The new rule took effect Sept. 1, 2021…",
            "url": "https://thenextweb.com/news/5-reasons-video-games-mandatory-classroom-syndication",
            "urlToImage": "https://img-cdn.tnwcdn.com/image/tnw?filter_last=1&fit=1280%2C640&url=https%3A%2F%2Fcdn0.tnwcdn.com%2Fwp-content%2Fblogs.dir%2F1%2Ffiles%2F2021%2F09%2Fpexels-julia-m-cameron-4144293.jpg&signature=e20b3669cc0054e963c0877546267b27",
            "publishedAt": "2021-09-11T08:00:45Z",
            "content": "In an effort to curtail how much time young people spend playing video games, China has banned students from playing them during the school week and limits them to just one hour per day on Fridays, w… [+6509 chars]",
        },
        {
            "source": {"id": "techcrunch", "name": "TechCrunch"},
            "author": "Connie Loizos",
            "title": "Tesla should say something",
            "description": "Last weekend, a reader wrote to this editor, politely asking why tech companies should speak up about the abortion law that Texas passed last week.  “What...",
            "url": "https://techcrunch.com/2021/09/10/tesla-should-say-something/",
            "urlToImage": "https://s.yimg.com/ny/api/res/1.2/_zz0MqwsTnD3Gf1q5Zabzg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://s.yimg.com/uu/api/res/1.2/Ai5rxUzq52l.M69oIw70ww--~B/aD0xNDE0O3c9MjEyMTthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/techcrunch_350/4ad3e99ddae4799d51a9ab52a4daa625",
            "publishedAt": "2021-09-11T05:37:56Z",
            "content": "Last weekend, a reader wrote to this editor, politely asking why tech companies should speak up about the abortion law that Texas passed last week.\r\nWhat does American Airlines have to do with aborti… [+4859 chars]",
        },
        {
            "source": {"id": "techcrunch", "name": "TechCrunch"},
            "author": "Connie Loizos",
            "title": "Tesla should say something",
            "description": "Last weekend, a reader wrote to this editor, politely asking why tech companies should speak up about the abortion law that Texas passed last week. “What does American Airlines have to do with abortion?” said the reader, suggesting that companies can’t possib…",
            "url": "http://techcrunch.com/2021/09/10/tesla-should-say-something/",
            "urlToImage": "https://techcrunch.com/wp-content/uploads/2019/03/Austin.jpg?w=600",
            "publishedAt": "2021-09-11T05:37:56Z",
            "content": "Last weekend, a reader wrote to this editor, politely asking why tech companies should speak up about the abortion law that Texas passed last week.\r\nWhat does American Airlines have to do with aborti… [+4856 chars]",
        },
        {
            "source": {"id": "techcrunch", "name": "TechCrunch"},
            "author": "Steve Gillmor",
            "title": "Gillmor Gang: Life Goes On – TechCrunch",
            "description": "When we imagine what it will be like when we exit the pandemic, what we’re really wondering is what we want from the digital transformation we’ve seen overturn our understanding of work and living safely. As much as we long for the days of the office and coll…",
            "url": "http://techcrunch.com/2021/09/10/gillmor-gang-life-goes-on/",
            "urlToImage": "https://techcrunch.com/wp-content/uploads/2020/07/F06D2685-6169-42C0-AE3B-D2545A1B3534.jpeg?w=711",
            "publishedAt": "2021-09-11T03:36:20Z",
            "content": "When we imagine what it will be like when we exit the pandemic, what we’re really wondering is what we want from the digital transformation we’ve seen overturn our understanding of work and living sa… [+4673 chars]",
        },
    ]
    return render_template("index.html", sources=sources, articles=articles)
